# Generated by Django 3.2.12 on 2022-06-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('url', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=500, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nomad.region')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('url', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=500, null=True)),
                ('near_coworking_spaces', models.ManyToManyField(related_name='Near_Accommodations', to='app_nomad.Coworking')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nomad.region')),
            ],
        ),
    ]
