# Generated by Django 3.2.12 on 2022-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nomad', '0003_auto_20220614_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='near_coworking_spaces',
            field=models.ManyToManyField(blank=True, null=True, related_name='Near_Accommodations', to='app_nomad.Coworking'),
        ),
    ]
